import type { Employee } from './types'

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: '1',
    name: 'André Pereira',
    initials: 'AP',
    colorKey: 'purple',
    role: 'Gerente',
    shift: 'Turno Integral',
    status: 'Em turno',
    salesToday: 38,
    commission: 171.0,
  },
  {
    id: '2',
    name: 'Júlia Andrade',
    initials: 'JA',
    colorKey: 'accent',
    role: 'Atendente',
    shift: 'Turno Manhã',
    status: 'Em turno',
    salesToday: 52,
    commission: 234.0,
  },
  {
    id: '3',
    name: 'Lucas Martins',
    initials: 'LM',
    colorKey: 'orange',
    role: 'Atendente',
    shift: 'Turno Tarde',
    status: 'Fora do turno',
    salesToday: 41,
    commission: 184.5,
  },
  {
    id: '4',
    name: 'Beatriz Rocha',
    initials: 'BR',
    colorKey: 'pink',
    role: 'Caixa',
    shift: 'Turno Tarde',
    status: 'Em pausa',
    salesToday: 28,
    commission: 126.0,
  },
  {
    id: '5',
    name: 'Felipe Souza',
    initials: 'FS',
    colorKey: 'blue',
    role: 'Estoquista',
    shift: 'Turno Manhã',
    status: 'Fora do turno',
    salesToday: 0,
    commission: 0,
  },
]
