import { CustomerMetrics, Customer } from '../../types/customers.types'

export const MOCK_CUSTOMER_METRICS: CustomerMetrics = {
  totalCustomers: 14,
  newCustomersThisMonth: 3,
  activeCustomers: 12,
  activePercentage: 86,
  averageLTV: 1013.2,
  vipCount: 4,
}

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: '1',
    name: 'Rafael Oliveira',
    phone: '(11) 99182-7733',
    email: 'rafael.oliveira@email.com',
    city: 'São Paulo, SP',
    segment: 'VIP',
    totalSpent: 3120.8,
    visits: 68,
    averageTicket: 45.89,
    lastPurchase: 'ontem',
    joinedDate: '03/2024',
    isVIP: true,
    favoriteItem: 'Café espresso 50g',
  },
  {
    id: '2',
    name: 'Mariana Costa',
    phone: '(11) 99432-1140',
    email: 'mariana.costa@gmail.com',
    city: 'São Paulo, SP',
    segment: 'VIP',
    totalSpent: 1842.5,
    visits: 42,
    averageTicket: 43.87,
    lastPurchase: 'há 2 horas',
    joinedDate: '03/2024',
    isVIP: true,
    favoriteItem: 'Café espresso 50g',
    notes: 'Cliente muito leal',
  },
  {
    id: '3',
    name: 'Marcos Vinicius',
    phone: '(11) 99201-1133',
    email: 'marcos.v@email.com',
    city: 'São Paulo, SP',
    segment: 'Inativo',
    totalSpent: 1612.0,
    visits: 36,
    averageTicket: 44.78,
    lastPurchase: 'há 3 meses',
    joinedDate: '06/2023',
    isVIP: false,
  },
  {
    id: '4',
    name: 'Diego Marques',
    phone: '(11) 99815-7700',
    email: 'diego.m@email.com',
    city: 'São Paulo, SP',
    segment: 'VIP',
    totalSpent: 1402.0,
    visits: 31,
    averageTicket: 45.23,
    lastPurchase: 'há 4 horas',
    joinedDate: '04/2024',
    isVIP: true,
  },
  {
    id: '5',
    name: 'Camila Souza',
    phone: '(11) 97001-2240',
    email: 'camila.souza@email.com',
    city: 'São Paulo, SP',
    segment: 'Regular',
    totalSpent: 1245.0,
    visits: 28,
    averageTicket: 44.46,
    lastPurchase: 'há 3 dias',
    joinedDate: '05/2023',
    isVIP: false,
  },
  {
    id: '6',
    name: 'Ana Silva',
    phone: '(11) 98765-4321',
    email: 'ana.silva@email.com',
    city: 'Rio de Janeiro, RJ',
    segment: 'Novo',
    totalSpent: 250.5,
    visits: 6,
    averageTicket: 41.75,
    lastPurchase: 'há 5 dias',
    joinedDate: '05/2026',
    isVIP: false,
  },
  {
    id: '7',
    name: 'Carlos Ribeiro',
    phone: '(11) 98432-1098',
    email: 'carlos.r@email.com',
    city: 'São Paulo, SP',
    segment: 'Regular',
    totalSpent: 980.25,
    visits: 22,
    averageTicket: 44.56,
    lastPurchase: 'há 1 dia',
    joinedDate: '02/2024',
    isVIP: false,
  },
  {
    id: '8',
    name: 'Beatriz Santos',
    phone: '(11) 99876-5432',
    email: 'beatriz.santos@email.com',
    city: 'Campinas, SP',
    segment: 'Novo',
    totalSpent: 180.0,
    visits: 4,
    averageTicket: 45.0,
    lastPurchase: 'há 2 dias',
    joinedDate: '05/2026',
    isVIP: false,
  },
  {
    id: '9',
    name: 'Felipe Costa',
    phone: '(11) 97654-3210',
    email: 'felipe.costa@email.com',
    city: 'São Paulo, SP',
    segment: 'Regular',
    totalSpent: 1125.75,
    visits: 25,
    averageTicket: 45.03,
    lastPurchase: 'há 6 dias',
    joinedDate: '01/2024',
    isVIP: false,
  },
  {
    id: '10',
    name: 'Lucia Martins',
    phone: '(11) 98765-1234',
    email: 'lucia.martins@email.com',
    city: 'São Paulo, SP',
    segment: 'Inativo',
    totalSpent: 890.0,
    visits: 20,
    averageTicket: 44.5,
    lastPurchase: 'há 2 meses',
    joinedDate: '08/2023',
    isVIP: false,
  },
  {
    id: '11',
    name: 'Roberto Alves',
    phone: '(11) 99543-2109',
    email: 'roberto.alves@email.com',
    city: 'Guarulhos, SP',
    segment: 'VIP',
    totalSpent: 2150.0,
    visits: 48,
    averageTicket: 44.79,
    lastPurchase: 'hoje',
    joinedDate: '02/2024',
    isVIP: true,
  },
  {
    id: '12',
    name: 'Juliana Pereira',
    phone: '(11) 98901-2345',
    email: 'juliana.p@email.com',
    city: 'São Paulo, SP',
    segment: 'Novo',
    totalSpent: 320.0,
    visits: 8,
    averageTicket: 40.0,
    lastPurchase: 'há 1 dia',
    joinedDate: '05/2026',
    isVIP: false,
  },
  {
    id: '13',
    name: 'Gustavo Lima',
    phone: '(11) 97890-1234',
    email: 'gustavo.lima@email.com',
    city: 'São Paulo, SP',
    segment: 'Regular',
    totalSpent: 750.5,
    visits: 17,
    averageTicket: 44.15,
    lastPurchase: 'há 4 dias',
    joinedDate: '03/2024',
    isVIP: false,
  },
  {
    id: '14',
    name: 'Patricia Gomes',
    phone: '(11) 99234-5678',
    email: 'patricia.gomes@email.com',
    city: 'São Paulo, SP',
    segment: 'Inativo',
    totalSpent: 612.0,
    visits: 14,
    averageTicket: 43.71,
    lastPurchase: 'há 4 meses',
    joinedDate: '09/2023',
    isVIP: false,
  },
]
